#!/bin/bash
# setup environment for Make-based development on Linux

if ! ([ "$OSTYPE" = "GNU/Linux" ] || [ "$OSTYPE" = "linux-gnu" ]); then
    echo error: not a linux system. Exiting
    exit 1
fi

# option to feed in arm eabi gcc compiler path (e.g. ./setup /your/path/)
gnu_install_root=${1:-/usr/bin/} # "return false if $1 is unset or an empty string"

gnu_prefix=$( ls ${gnu_install_root} | grep -o "arm-.*-eabi" | head -1 )

if ${gnu_prefix}-gcc -v &> /dev/null; then
    echo setting up environment for Make-based development
    gnu_version=$(${gnu_prefix}-gcc --version | egrep -o "[0-9]{1,2}\.[0-9]\.[0-9]" | head -1)
else
    echo embedded gcc not installed. Trying to install
    sudo apt install gcc-arm-none-eabi
fi

echo install root: ${gnu_install_root}
echo prefix: ${gnu_prefix}-gcc
echo version: ${gnu_version}

# update Makefile.posix
path_to_makefile_posix=nRF5_SDK_15.2.0_9412b96/components/toolchain/gcc/Makefile.posix
echo updating Makefile.posix

if 
sed -i "s|GNU_INSTALL_ROOT ?=.*|GNU_INSTALL_ROOT ?= ${gnu_install_root}|g" ${path_to_makefile_posix} && \
sed -i "s|GNU_VERSION ?=.*|GNU_VERSION ?= ${gnu_version}|g" ${path_to_makefile_posix} && \
sed -i "s|GNU_PREFIX ?=.*|GNU_PREFIX ?= ${gnu_prefix}|g" ${path_to_makefile_posix}
then
    echo compiler setup complete
else
    echo compiler setup failed
fi

if ! "nrfjprog" &> /dev/null; then
    echo download nrfjprog from https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-Command-Line-Tools/Download.\
    Follow the README and restart your pc after downloading JLINK
fi